# Generated by Django 4.2.23 on 2025-10-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="user_ref",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("waiting_agent", "Waiting agent"),
                    ("agent_joined", "Agent joined"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("abandoned", "Abandoned"),
                ],
                db_index=True,
                default="open",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="visitor_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["updated_at"], name="support_app_updated_a46c1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["status", "updated_at"], name="support_app_status_082ea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "id"], name="support_app_session_c2d1a3_idx"
            ),
        ),
    ]
