# Generated by Django 4.2.23 on 2025-10-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0002_chatsession_user_ref_alter_chatsession_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client_nonce",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["session", "client_nonce"],
                name="support_app_session_11ca02_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_nonce", None), _negated=True),
                fields=("session", "client_nonce"),
                name="uniq_session_client_nonce",
            ),
        ),
    ]
