# Generated by Django 4.2.23 on 2025-10-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_app", "0003_message_client_nonce_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="kind",
            field=models.CharField(
                choices=[
                    ("agent_requested", "Agent requested"),
                    ("agent_joined", "Agent joined"),
                    ("agent_left", "Agent left"),
                    ("bot_suppressed", "Bot suppressed"),
                    ("resolved", "Resolved"),
                    ("reopened", "Reopened"),
                    ("email_sent", "Email sent"),
                    ("telegram_sent", "Telegram sent"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["session", "id"], name="support_app_session_456503_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["session", "created_at"], name="support_app_session_a047dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["kind", "created_at"], name="support_app_kind_9ff732_idx"
            ),
        ),
    ]
