# Generated by Django 4.2.23 on 2025-08-23 13:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('invitation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('avatar_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signup_country', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_login_country', models.CharField(blank=True, max_length=100, null=True)),
                ('tx_pin_hash', models.CharField(blank=True, max_length=128)),
                ('tx_pin_changed_at', models.DateTimeField(blank=True, null=True)),
                ('tx_pin_attempts', models.PositiveIntegerField(default=0)),
                ('tx_pin_locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', main.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-pinned', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('iso', models.CharField(db_index=True, max_length=2, unique=True)),
                ('flag', models.CharField(blank=True, help_text='Emoji flag (e.g., 🇩🇪)', max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('ETH', 'Ethereum (ERC20)'), ('TRC20', 'USDT (TRC20)')], max_length=10, unique=True)),
                ('address', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('about', 'About us'), ('contact', 'Contact us'), ('help', 'Help'), ('level', 'Level'), ('signin_reward', 'Sign-in reward')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='PayoutAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=64)),
                ('address_type', models.CharField(choices=[('ETH', 'Ethereum (ERC-20)'), ('TRC20', 'USDT (TRC-20)')], max_length=10)),
                ('address', models.CharField(max_length=128)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_task_cost_cents', models.PositiveIntegerField(default=1200)),
                ('trial_commission_cents', models.PositiveIntegerField(default=145)),
                ('trial_max_tasks', models.PositiveIntegerField(default=25)),
                ('normal_task_limit', models.PositiveIntegerField(default=3)),
                ('normal_commission_cents', models.PositiveIntegerField(default=200)),
                ('normal_worth_cents', models.PositiveIntegerField(default=0)),
                ('vip_default_commission_cents', models.PositiveIntegerField(default=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_cents', models.BigIntegerField(default=0)),
                ('bonus_cents', models.BigIntegerField(default=0)),
                ('pending_cents', models.BigIntegerField(default=0)),
                ('trial_bonus_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'Pound (£)')], default='EUR', max_length=3)),
                ('fee_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.payoutaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('TRIAL', 'Trial'), ('NORMAL', 'Normal'), ('VIP', 'VIP')], db_index=True, default='TRIAL', max_length=10)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('country', models.CharField(db_index=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tasks/covers/%Y/%m/')),
                ('cover_image_url', models.URLField(blank=True)),
                ('order_code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Order ID')),
                ('order_date', models.DateField(blank=True, null=True)),
                ('worth_cents', models.PositiveIntegerField(default=0, help_text='€ in cents, e.g. 15000 = €150.00')),
                ('commission_cents', models.PositiveIntegerField(default=0, help_text='€ in cents, e.g. 350 = €3.50')),
                ('score', models.DecimalField(decimal_places=1, help_text='0.0 – 5.0 (one decimal)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('label', models.CharField(choices=[('perfect', 'Perfect'), ('good', 'Good'), ('medium', 'Medium')], default='good', help_text='Chip on card (color-coded)', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-score', 'name'],
                'indexes': [models.Index(fields=['phase', 'is_published'], name='main_taskte_phase_4f0758_idx'), models.Index(fields=['-created_at'], name='main_taskte_created_204648_idx'), models.Index(fields=['-score'], name='main_taskte_score_c5183b_idx'), models.Index(fields=['-popularity'], name='main_taskte_popular_86dfaf_idx'), models.Index(fields=['country'], name='main_taskte_country_7b4be6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('description_short', models.CharField(max_length=200, verbose_name='Text under it')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='hotels/covers/')),
                ('cover_image_url', models.URLField(blank=True)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=1, help_text='0.0 – 5.0 (one decimal)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('label', models.CharField(choices=[('perfect', 'Perfect'), ('good', 'Good'), ('medium', 'Medium')], default='good', help_text='Chip on card (color-coded)', max_length=10)),
                ('is_recommended', models.BooleanField(default=False)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='main.country')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_hotels', through='main.Favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-score', 'name'],
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotel'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('txid', models.CharField(blank=True, max_length=128, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'Pound (£)')], default='EUR', max_length=3)),
                ('network', models.CharField(choices=[('ETH', 'Ethereum (ERC20)'), ('TRC20', 'USDT (TRC20)')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_review', 'Awaiting Review'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='awaiting_payment', max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('pay_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.depositaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('BONUS', 'Bonus'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('ADJUST', 'Adjust')], max_length=20)),
                ('bucket', models.CharField(choices=[('CASH', 'Cash'), ('BONUS', 'Bonus')], default='CASH', max_length=10)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txns', to='main.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='main_wallet_wallet__e17687_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('TRIAL', 'Trial'), ('NORMAL', 'Normal'), ('VIP', 'VIP')], db_index=True, max_length=10)),
                ('index_in_phase', models.PositiveIntegerField()),
                ('cost_cents', models.IntegerField(default=0)),
                ('commission_cents', models.IntegerField(default=0)),
                ('worth_cents', models.IntegerField(default=0)),
                ('deposit_required_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], db_index=True, default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(help_text='Prevents double-processing', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='main.tasktemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'phase', 'status'], name='main_task_user_id_ae3ad6_idx')],
                'unique_together': {('user', 'phase', 'index_in_phase')},
            },
        ),
        migrations.AddIndex(
            model_name='payoutaddress',
            index=models.Index(fields=['user', 'address_type'], name='main_payout_user_id_b92e6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutaddress',
            constraint=models.UniqueConstraint(fields=('user', 'address_type'), name='uniq_user_network_address'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['-created_at'], name='main_hotel_created_71749b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['-score'], name='main_hotel_score_022c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['-popularity'], name='main_hotel_popular_67efea_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_recommended'], name='main_hotel_is_reco_f9f75b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_published'], name='main_hotel_is_publ_8966c0_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['country'], name='main_hotel_country_1ea9aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'hotel')},
        ),
    ]
