# Generated by Django 4.2.23 on 2025-08-23 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('AUTO', 'Auto (computed)'), ('MANUAL', 'Manual (admin override)')], db_index=True, default='AUTO', max_length=10)),
                ('total_assets_cents', models.BigIntegerField(default=0)),
                ('asset_cents', models.BigIntegerField(default=0)),
                ('dividends_cents', models.BigIntegerField(default=0)),
                ('processing_cents', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_display', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Display',
                'verbose_name_plural': 'Account Displays',
                'indexes': [models.Index(fields=['mode'], name='main_accoun_mode_663bc1_idx')],
            },
        ),
    ]
