# Generated by Django 4.2.23 on 2025-08-10 09:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('iso', models.CharField(max_length=2, unique=True)),
                ('flag', models.CharField(blank=True, help_text='Emoji flag (e.g., 🇩🇪)', max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('description_short', models.CharField(max_length=200, verbose_name='Text under it')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='hotels/covers/')),
                ('available_date', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=1, help_text='0.0 – 5.0 (one decimal)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('label', models.CharField(choices=[('perfect', 'Perfect'), ('good', 'Good'), ('medium', 'Medium')], default='good', help_text='Chip on card (color-coded)', max_length=10)),
                ('is_recommended', models.BooleanField(default=False)),
                ('popularity', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='main.country')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_hotels', through='main.Favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-score', 'name'],
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotel'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'hotel')},
        ),
    ]
