# Generated by Django 4.2.23 on 2025-08-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='trial_bonus_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
