# Generated by Django 4.2.23 on 2025-08-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_favorite_hotel_favorite_hotel_favorite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(db_index=True, max_length=2, unique=True),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['-created_at'], name='main_hotel_created_71749b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['-score'], name='main_hotel_score_022c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['-popularity'], name='main_hotel_popular_67efea_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_recommended'], name='main_hotel_is_reco_f9f75b_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_published'], name='main_hotel_is_publ_8966c0_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['country'], name='main_hotel_country_1ea9aa_idx'),
        ),
    ]
