# Generated by Django 4.2.23 on 2025-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_accountdisplay"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="require_reset_after_trial",
            field=models.BooleanField(
                default=True,
                help_text="When ON, once a user completes the 25th trial task, they are blocked from doing further tasks (Trial/Normal/VIP) until an admin resets/unblocks them.",
            ),
        ),
    ]
