# Generated by Django 4.2.23 on 2025-08-16 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wallet_trial_bonus_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('BONUS', 'Bonus'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('ADJUST', 'Adjust')], max_length=20)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txns', to='main.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='main_wallet_wallet__e17687_idx')],
            },
        ),
    ]
