# Generated by Django 4.2.23 on 2025-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_systemsettings_require_reset_after_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="trial_gate_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trial_gate_blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trial_gate_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
