# Generated by Django 4.2.23 on 2025-08-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wallettxn'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount_cents',
            field=models.BigIntegerField(default=0),
        ),
    ]
