# Generated by Django 4.2.23 on 2025-08-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_depositaddress_payoutaddress_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='txid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
