# Generated by Django 4.2.23 on 2025-08-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wallet_amount_cents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='amount_cents',
        ),
        migrations.AddField(
            model_name='wallet',
            name='bonus_cents',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallettxn',
            name='bucket',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BONUS', 'Bonus')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallettxn',
            name='amount_cents',
            field=models.BigIntegerField(default=0),
        ),
    ]
