# Generated by Django 4.2.23 on 2025-08-26 21:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_customuser_trial_gate_blocked_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="tasksettngs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_limit_per_cycle",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Number of tasks allowed in a cycle before the user is blocked.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "block_on_reaching_limit",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, the user becomes blocked immediately upon reaching the cycle limit.",
                    ),
                ),
                (
                    "block_message",
                    models.CharField(
                        default="Trial limit reached. Please contact customer care to continue.",
                        help_text="Shown to the user when blocked.",
                        max_length=255,
                    ),
                ),
                (
                    "task_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("12.00"),
                        help_text="Optional per-task charge (set 0.00 if not used).",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "task_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.45"),
                        help_text="Commission paid to the user per completed task.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "clear_trial_bonus_at_limit",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, the user's trial bonus will be cleared when they hit the cycle limit.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Settings",
                "verbose_name_plural": "Task Settings",
            },
        ),
    ]
