# Generated by Django 4.2.23 on 2025-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customuser_avatar_customuser_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tx_pin_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tx_pin_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tx_pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tx_pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
