# Generated by Django 4.2.23 on 2025-08-27 10:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_usertasktemplate_delete_usertaskprogress_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTaskProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycles_completed", models.PositiveIntegerField(default=0)),
                (
                    "current_task_index",
                    models.PositiveIntegerField(
                        default=0, help_text="0-based; next visible = index + 1"
                    ),
                ),
                ("is_blocked", models.BooleanField(db_index=True, default=False)),
                ("limit_snapshot", models.PositiveIntegerField(default=25)),
                (
                    "price_snapshot",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=12
                    ),
                ),
                (
                    "commission_snapshot",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.45"), max_digits=12
                    ),
                ),
                ("last_reset_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="main_userta_user_id_67ffa4_idx"
                    ),
                    models.Index(
                        fields=["is_blocked"], name="main_userta_is_bloc_7d88da_idx"
                    ),
                ],
            },
        ),
    ]
