# Generated by Django 4.2.23 on 2025-08-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_usertaskprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
