# Generated by Django 4.2.23 on 2025-08-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_usertask_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountdisplay",
            name="user",
        ),
        migrations.DeleteModel(
            name="SystemSettings",
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="template",
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="trial_gate_blocked",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="trial_gate_blocked_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="trial_gate_reset_at",
        ),
        migrations.DeleteModel(
            name="AccountDisplay",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskTemplate",
        ),
    ]
