# Generated by Django 4.2.23 on 2025-08-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_accountdisplay_user_delete_systemsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaskprogress",
            name="asset_cents",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usertaskprogress",
            name="dividends_cents",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usertaskprogress",
            name="processing_cents",
            field=models.BigIntegerField(default=0),
        ),
    ]
