# Generated by Django 4.2.23 on 2025-08-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_usertaskprogress_asset_cents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertask",
            name="required_cash_cents",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usertask",
            name="snapshot_total_at_assignment_cents",
            field=models.BigIntegerField(default=0),
        ),
    ]
