# Generated by Django 4.2.23 on 2025-08-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_usertask_required_cash_cents_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertask",
            old_name="snapshot_total_at_assignment_cents",
            new_name="assignment_total_display_cents",
        ),
    ]
