# Generated by Django 4.2.23 on 2025-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0013_rename_snapshot_total_at_assignment_cents_usertask_assignment_total_display_cents",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaskprogress",
            name="dividends_paid_cents",
            field=models.BigIntegerField(default=0),
        ),
    ]
