# Generated by Django 4.2.23 on 2025-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_usertaskprogress_dividends_paid_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettxn",
            name="external_ref",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddIndex(
            model_name="wallettxn",
            index=models.Index(
                fields=["wallet", "external_ref"], name="main_wallet_wallet__5272f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettxn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_ref", ""), _negated=True),
                fields=("wallet", "external_ref"),
                name="uniq_wallet_external_ref",
            ),
        ),
    ]
