# Generated by Django 4.2.23 on 2025-09-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_wallettxn_external_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaskprogress",
            name="last_withdraw_cycle",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
