# Generated by Django 4.2.23 on 2025-09-03 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_usertaskprogress_last_withdraw_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksettngs",
            name="cycles_between_withdrawals",
            field=models.PositiveIntegerField(
                default=2,
                help_text="How many full cycles must be completed between withdrawals.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
