# Generated by Django 4.2.23 on 2025-09-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_tasksettngs_cycles_between_withdrawals"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaskprogress",
            name="has_admin_ever",
            field=models.BooleanField(default=False),
        ),
    ]
