# Generated by Django 4.2.23 on 2025-09-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_usertaskprogress_has_admin_ever"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertaskprogress",
            name="has_admin_ever",
        ),
    ]
