# Generated by Django 4.2.23 on 2025-09-24 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_customuser_invited_by_invitationcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("claimed", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="invitationusage",
            name="code",
        ),
        migrations.RemoveField(
            model_name="invitationusage",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="invitation_code_used",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="invited_by",
        ),
        migrations.DeleteModel(
            name="InvitationCode",
        ),
        migrations.DeleteModel(
            name="InvitationUsage",
        ),
        migrations.AddField(
            model_name="invitationlink",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invites_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitationlink",
            name="used_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_used",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
