# Generated by Django 4.2.23 on 2025-09-28 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_invitationlink_remove_invitationusage_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payoutaddress",
            name="address_type",
            field=models.CharField(
                choices=[("ETH", "Ethereum (ERC20)"), ("TRC20", "USDT (TRC20)")],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="UserCycleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_number", models.PositiveIntegerField()),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="main_usercy_user_id_8bcb42_idx"
                    )
                ],
                "unique_together": {("user", "cycle_number")},
            },
        ),
        migrations.CreateModel(
            name="SigninRewardLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("amount_cents", models.IntegerField(default=0)),
                ("is_bonus", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signin_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="main_signin_user_id_608ea4_idx"
                    ),
                    models.Index(
                        fields=["user", "is_bonus"],
                        name="main_signin_user_id_439c9c_idx",
                    ),
                ],
                "unique_together": {("user", "date", "is_bonus")},
            },
        ),
    ]
