# Generated by Django 4.2.23 on 2025-09-28 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_payoutaddress_address_type_usercyclelog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCycleSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "cycles_completed_at_midnight",
                    models.PositiveIntegerField(default=0),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="main_dailyc_user_id_8cf531_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
