# Generated by Django 4.2.23 on 2025-09-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_dailycyclesnapshot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCycleLog",
        ),
    ]
