# Generated by Django 4.2.23 on 2025-09-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_delete_usercyclelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaskprogress",
            name="first_reward_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
