# Generated by Django 4.2.23 on 2025-09-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_usertaskprogress_first_reward_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forcedtaskdirective",
            options={
                "ordering": ["target_order", "created_at"],
                "verbose_name": "Special order",
                "verbose_name_plural": "Special orders",
            },
        ),
    ]
