# Generated by Django 4.2.23 on 2025-10-01 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_alter_forcedtaskdirective_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FortuneCardRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("CASH", "Cash reward"), ("GOLDEN", "Golden (admin)")],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "cycle_number",
                    models.PositiveIntegerField(
                        help_text="Cycle to match (0 = first cycle)."
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        help_text="1-based order inside the cycle."
                    ),
                ),
                ("reward_amount_cents", models.BigIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fortune_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "golden_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin task to spawn for GOLDEN rewards.",
                        limit_choices_to={"is_admin_task": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.usertasktemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FortuneCardGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_number", models.PositiveIntegerField()),
                ("order_index", models.PositiveIntegerField()),
                ("kind", models.CharField(default="CASH", max_length=10)),
                ("amount_cents", models.BigIntegerField(default=0)),
                ("golden_template_id", models.IntegerField(default=0)),
                ("picked_box", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFFERED", "Offered"),
                            ("CLICKED", "Clicked"),
                            ("CREDITED", "Credited (cash)"),
                            ("CONVERTED", "Converted to task (golden)"),
                            ("CANCELED", "Canceled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="OFFERED",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="main.fortunecardrule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fortune_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fortune_origin",
                        to="main.usertask",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="fortunecardrule",
            index=models.Index(
                fields=["active", "cycle_number", "order_index"],
                name="main_fortun_active_ab4c9f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fortunecardrule",
            index=models.Index(
                fields=["expires_at"], name="main_fortun_expires_0be17b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fortunecardgrant",
            index=models.Index(
                fields=["user", "cycle_number", "order_index"],
                name="main_fortun_user_id_3ca66b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fortunecardgrant",
            index=models.Index(fields=["status"], name="main_fortun_status_bc5d97_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="fortunecardgrant",
            unique_together={("user", "cycle_number", "order_index")},
        ),
    ]
