# Generated by Django 4.2.23 on 2025-10-01 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_fortunecardrule_fortunecardgrant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fortunecardrule",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only this user sees the card at that slot.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fortune_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="fortunecardrule",
            index=models.Index(
                fields=["target_user", "cycle_number", "order_index"],
                name="main_fortun_target__89b699_idx",
            ),
        ),
    ]
